name: paper-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - libffi
  - openssl
  - pip
  - python=3.11
  - setuptools
  - sqlite
  - tk
  - tzdata
  - xz
  - zlib
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.0
      - attrs==24.2.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==43.0.1
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - elastic-transport==8.15.0
      - elasticsearch==8.15.1
      - faiss-cpu==1.8.0.post1
      - fastapi==0.115.0
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - jinja2==3.1.4
      - jiter==0.5.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.2
      - langchain-community==0.3.1
      - langchain-core==0.3.9
      - langchain-openai==0.2.2
      - langchain-text-splitters==0.3.0
      - langchainhub==0.1.21
      - langsmith==0.1.131
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - networkx==3.3
      - numpy==1.26.4
      - openai==1.51.0
      - orjson==3.10.7
      - outcome==1.3.0.post0
      - packaging==24.1
      - pdfminer-six==20231228
      - pdfplumber==0.11.4
      - pillow==10.4.0
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.5.2
      - pypdfium2==4.30.0
      - pysocks==1.7.1
      - python-dotenv==1.0.1
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - selenium==4.25.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.35
      - starlette==0.38.6
      - sympy==1.13.3
      - tenacity==8.5.0
      - tiktoken==0.8.0
      - torch==2.4.1
      - tqdm==4.66.5
      - trio==0.26.2
      - trio-websocket==0.11.1
      - types-requests==2.32.0.20240914
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - urllib3==2.2.3
      - uvicorn==0.31.0
      - websocket-client==1.8.0
      - wget==3.2
      - wsproto==1.2.0
      - yarl==1.13.1
      - pymupdf4llm==0.0.17
